databases:
  - name: coachingappdb
    plan: free
    databaseName: coachingappdb
    user: coachingapp

services:
  - type: web
    plan: free
    name: coachingapp
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn coachingapp.asgi:application -k uvicorn.workers.UvicornWorker' 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: coachingappdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4